### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-datastore#18]
It's possible to generate API docs via `npm run doc`, but they need to be published.

Ideally:
* available at `https://mozilla-lockbox.github.io/lockbox-datastore`
* built on each master commit/merge

**Comment by devinreams** [comment]
@linuxwolf @jimporter I played around a little last night to find a "good" path here. What do you think of this?

![blank](https://user-images.githubusercontent.com/49511/30597586-a36e4004-9d14-11e7-81d3-14a994ea627e.png)

1. run jsdox (instead of jsdoc) against `/lib`, put resulting markdown in `/docs/api/`
2. configure `/docs/` to run Jekyll / GitHub Pages

This way we don't have a ton of HTML (and related assets) checked in but do have legible markdown docs in `docs` _in addition to_ a published website based on everything we put in `docs`.

A couple small concerns:

- jsdox only supports a subset of jsdoc3 (but looking at the results side-by-side, they appeared identical, thus far)
- I didn't find a good way to do a post-push hook to build the docs (step 1), those would have to be checked-in by us (but perhaps opens us up to a good practice to include `run doc` in `package` so the author sees changes resulted in doc changes?)

What do you think?

**Comment by linuxwolf** [comment]
I'd much rather the docs got generated on each merge into master.

The flow I've seen is to have Travis push a commit to the `gh-pages` branch when building on `master`.  The [gh-pages](https://www.npmjs.com/package/gh-pages) might help here.

If you're going to research that (which creates branches and pushes stuff automatically), please do it on a fork.

**Comment by linuxwolf** [comment]
From my quick perusal, the jsdox output seem to be missing the following:

* `datastore.initialized` (uses @type)
* `datastore.locked` (uses @type)
* `open()` (uses @memberof)

**Comment by devinreams** [comment]
>From my quick perusal, the jsdox output seem to be missing the following..

Ah sorry I missed that. It's probably not worth pursuing jsdox further for now then...

**Comment by devinreams** [comment]
Ah yeah, `jsdoc2md` could be slick.

We could actually create custom handlebars to pipe the markdown through and create Jekyll frontmatter so that all of `/docs` can be served as HTML. 🤔 

The auto-build-and-commit from Travis would be very nice. Ideally this all can stay on "master" so docs is legible and available to anyone, whether they look at the repo or the website.

Either way, I will play with this a bit and see if I can help hook things up...

**Comment by devinreams** [comment]
Closed at #32
